Hamburger_links:
  type: list
  list_type: simple
  default: "Tudástér,/docs,g,lightbulb|Videótár,/pub/videotar,g,video,blank|VapeDIY,https://diy.vaperina.cc,g,flask,blank|Vaper Lokátor,/u/user-map?period=location,g,compass|Felhasználók,/u,g,user|Csoportok,/g,g,users|Kitüntetések,/badges,g,certificate|Torta Nap!,/cakeday/anniversaries/today,g,birthday-cake"
  description:
    en: 'Comma delimited in this order: Text,URL,Location,Target.<br><b>Text:</b> what appears on the menu.<br><b>URL:</b> the path for the link.<br><b>Location:</b> where you want the link to appear. Use "g" for generalLinks and "f" for footerLinks.<br><b>Target (optional):</b> use "blank" to open the link in a new tab.'
